"""users table
Revision ID: b0f022d7e488
Revises: 932fc5b92105
Create Date: 2020-12-29 14:35:04.006672
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f022d7e488'
down_revision = '932fc5b92105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('basis', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('degree', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('group', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'year')
    op.drop_column('user', 'group')
    op.drop_column('user', 'education')
    op.drop_column('user', 'degree')
    op.drop_column('user', 'basis')
    # ### end Alembic commands ###